### ISSUE TITLE
Mouse click interfering with pointer lock in Chrome

### ISSUE THREAD

**Issue by SpaceHexagon** [Convolvr/convolvr#126]

**Comment by SpaceHexagon** [comment]
only happening on one of my windows pcs.. strange

**Comment by SpaceHexagon** [comment]
not happening on raspberry pi either

**Comment by ds0nt** [comment]
I shall give it a whirl when im at my computer :p

**Comment by SpaceHexagon** [comment]
@ds0nt switch to branch task/98 and try left clicking or right clicking  (holding down) while controlling the camera (and turning more than slightly)
