### ISSUE TITLE
Finish Chat Modal

### ISSUE THREAD

**Issue by SpaceHexagon** [Convolvr/convolvr#140]

**Comment by ds0nt** [comment]
also, a hotkey to dismiss it from the keyboard.

like what was annoying is whenever chat starts, i have to click the x I
think. So if a some messages are happening I cant really do much

**Comment by SpaceHexagon** [comment]
I kind of switched it around so <kbd>esc</kbd> exits 3d mode and opens the menu, but my solution for now, is to not open the chat / 2d ui at all, if currently controlling it. the modal I'm working on, would appear below / in front of you, but not be stuck to you, you'd move away from it

**Comment by SpaceHexagon** [comment]
Hmm.. could make it so instead of sending an empty message, hitting enter closes chat also

**Comment by SpaceHexagon** [comment]
Note to self: the current user creates its chat-text component with the wrong ```props.chat.userId```
