### ISSUE TITLE
Update ticks (for systems that need them) in occupied voxels (server side)

### ISSUE THREAD

**Issue by SpaceHexagon** [Convolvr/convolvr#51]
Ideally, this could be configured by the settings of the particular world on the database.

**Comment by ds0nt** [comment]
Ooooh, github issues.

**Comment by SpaceHexagon** [comment]
I thought about it some more, and terrain / chunk generation should also probably happen on the server (due to ways the seeding can go out of sync between clients). Still, even if terrain can be consistently generated in the browser, its alterations should at least be served from an endpoint.

**Comment by ds0nt** [comment]
Yeah, I agree. Let's put it on the server and keep it simple

**Comment by SpaceHexagon** [comment]
Maybe some kind of "deep tick" that keeps going after everyone leaves too.. without wasting cpu

**Comment by SpaceHexagon** [comment]
Migrating this issue to the server repo https://github.com/Convolvr/server/issues/1
